//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Art_supplies.ApplicationData
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Products
    {
        public int ID { get; set; }
        public string Articul { get; set; }
        public int Name_product { get; set; }
        public int Unit { get; set; }
        public int Cost { get; set; }
        public Nullable<int> Max_discount { get; set; }
        public int Manufacturer { get; set; }
        public int Provider { get; set; }
        public int Category { get; set; }
        public Nullable<int> Real_discount { get; set; }
        public Nullable<int> In_stock { get; set; }
        public string Description { get; set; }
        public string IMG { get; set; }


        public string CurrentPhoto
        {
            get
            {
                if (string.IsNullOrEmpty(IMG) || String.IsNullOrWhiteSpace(IMG))
                {
                    return "S:\\USERS\\51-02\\Поливчак Алёна Олеговна\\Pr\\Товар_import\\Art_supplies\\Art_supplies\\Image\\picture.png";
                }
                else
                {
                    return "S:\\USERS\\51-02\\Поливчак Алёна Олеговна\\Pr\\Товар_import\\Art_supplies\\Art_supplies\\Image\\" + IMG;
                }
            }
        }

        public virtual Categories Categories { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual Names_products Names_products { get; set; }
        public virtual Providers Providers { get; set; }
        public virtual Units Units { get; set; }

    }
    
}
